service: recommendation-api

# Load environment variables from .env* files
# https://www.serverless.com/framework/docs/environment-variables/
useDotenv: true

provider:
  name: aws
  runtime: python3.8
  deploymentBucket:
    blockPublicAccess: true
  lambdaHashingVersion: 20201221
  logs:
    httpApi: true
  logRetentionInDays: 14
  environment:
    # ${env:*} variables are injected from the build-time environment.
    PROJECT_NAME: ${env:PROJECT_NAME}
    API_KEY: ${env:API_KEY}
    BASE_ID: ${env:BASE_ID}
    DEBUG: ${env:DEBUG}
  memorySize: 1024
  timeout: 750

package:
  exclude:
    # Remove any non-essential files from the deployment package
    - .direnv/**
    - .editorconfig
    - venv/**
    - .idea/**
    - .vscode/**
    - package*.json
    - Pipfile*
    - resources/*
    - setup.cfg
    - pyproject.toml
    - node_modules/**
    - .mypy_cache/**
    - .pytest_cache/**
    - .coverage
    - htmlcov/**
    - main.py
    - tests/**
    - src/adapters
    - src/logic
    - src/models

functions:
  app:
    handler: app.api.handler
    events:
      - httpApi:
          method: '*'
          # See https://github.com/dherault/serverless-offline/issues/1118
          path: ${env:CATCHALL_ROUTE, '*'}

plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
  serverless-offline:
    noPrependStageInUrl: true
